# Generated by Django 5.2.5 on 2025-09-02 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandas', '0002_alter_demanda_andamento_detalhado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da reunião', max_length=200)),
                ('data', models.DateField(help_text='Data da reunião')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Horário de início', null=True)),
                ('hora_fim', models.TimeField(blank=True, help_text='Horário de término', null=True)),
                ('local', models.CharField(blank=True, help_text='Local da reunião', max_length=200)),
                ('participantes', models.TextField(blank=True, help_text='Lista de participantes')),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do tópico', max_length=255)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de apresentação do tópico')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='reunioes.reuniao')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Descrição do ponto discutido')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de apresentação do ponto')),
                ('demanda', models.ForeignKey(blank=True, help_text='Demanda associada a este ponto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pontos_reuniao', to='demandas.demanda')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='reunioes.topico')),
            ],
            options={
                'verbose_name': 'Ponto',
                'verbose_name_plural': 'Pontos',
                'ordering': ['ordem'],
            },
        ),
    ]
