# Generated by Django 3.2.25 on 2025-08-29 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.TextField(verbose_name='Atividade')),
                ('data_insercao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inserção')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_termino', models.DateTimeField(blank=True, null=True, verbose_name='Data de Término')),
                ('andamento_detalhado', models.TextField(verbose_name='Andamento Detalhado')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Situação')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_supervisionadas', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
            },
        ),
    ]
