# Generated by Django 3.2.25 on 2025-08-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='andamento_detalhado',
            field=models.TextField(blank=True, verbose_name='Andamento Detalhado'),
        ),
    ]
