# Generated by Django 5.2.5 on 2025-09-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0002_alter_demanda_andamento_detalhado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='data_termino',
        ),
        migrations.AddField(
            model_name='demanda',
            name='categoria',
            field=models.CharField(choices=[('desenvolvimento', 'Desenvolvimento'), ('manutencao_correcao', 'Manutenção/Correção'), ('infraestrutura_devops', 'Infraestrutura/DevOps'), ('testes', 'Testes'), ('documentacao', 'Documentação'), ('administrativo', 'Administrativo'), ('outros', 'Outros')], default='outros', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='data_prevista',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Prevista'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='horas_executadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas Executadas'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='prioridade',
            field=models.CharField(choices=[('critica', 'Crítica / P0'), ('alta', 'Alta / P1'), ('media', 'Média / P2'), ('baixa', 'Baixa / P3')], default='baixa', max_length=50, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='situacao',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('em_andamento', 'Em Andamento'), ('em_espera', 'Em Espera'), ('em_teste', 'Em Teste'), ('em_revisao', 'Em Revisão'), ('resolvido', 'Resolvido'), ('rejeitado_cancelado', 'Rejeitado/Cancelado')], default='backlog', max_length=20, verbose_name='Situação'),
        ),
    ]
